baseURL = "https://keithhubner.github.io/keithhubner.com/"
title = "Keith Hubner"
theme = "PaperMod"

ignoreLogs = ["warning-partial-superfluous-prefix"]

[params]
  # Add theme-specific settings here
  author = "Keith Hubner"
  showDate = true
  favicon = "favicon.ico"
  disableRSS = false
  disableSitemap = false
  ShowCodeCopyButtons = true
  enableTOC = true
  contactLinks = [
    { name = "Email", url = "mailto:keith@hubner.co.uk" },
    { name = "LinkedIn", url = "https://linkedin.com/in/keithhubner" },
    { name = "GitHub", url = "https://github.com/keithhubner" }
  ]

  paginate = 10  # Number of posts per page
  paginatePath = "page"  # Path for paginated pages

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2