apiVersion: apps/v1
kind: Deployment
metadata:
  name: keithhubner-blog
  namespace: keithhubner-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keithhubner-blog
  template:
    metadata:
      labels:
        app: keithhubner-blog
    spec:
      containers:
        - name: keithhubner-blog
          image: ghcr.io/keithhubner/keithhubner.com/keithhubner-blog:latest
          ports:
            - containerPort: 80
          env:
            - name: HUGO_BASE_URL
              value: "https://blog.keithhubner.com"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: keithhubner-blog-service
  namespace: keithhubner-blog  
spec:
  selector:
    app: keithhubner-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP